import "@/styles/globals.css";
import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";

import { SidebarProvider } from "@/components/ui/sidebar";

import PfSidebar from "@/components/pf-components/pf-sidebar/pf-sidebar";

const publicSans = Public_Sans({
  variable: "--font-public-sans",
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${publicSans.variable} bg-parchment antialiased`}>
        <SidebarProvider>
          <PfSidebar />
          {children}
        </SidebarProvider>
      </body>
    </html>
  );
}
